* Backported some changes from Debian * debian/patches/39_grep_path.patch:   - Don’t hardcode grep to a wrong location. * debian/gdm.postrm:   - correctly deal with uninstalls while gdm is still running (lp: #613150)
(bzr r297)

diff --git a/debian/gdm.postrm b/debian/gdm.postrm
--- a/debian/gdm.postrm
+++ b/debian/gdm.postrm
@@ -14,12 +14,12 @@ if [ "$1" = "purge" ] ; then
         fi
         if getent passwd gdm >/dev/null; then
                 if [ -x /usr/sbin/deluser ]; then
-                        deluser --system gdm
+                        deluser --system gdm || echo "Could not remove gdm user."
                 fi
         fi
         if getent group gdm >/dev/null; then
                 if [ -x /usr/sbin/delgroup ]; then
-                        delgroup --system gdm
+                        delgroup --system gdm || echo "Could not remove gdm group."
                 fi
         fi
 fi
