+deluser

diff --git a/debian/gdm3.postrm b/debian/gdm3.postrm
--- a/debian/gdm3.postrm
+++ b/debian/gdm3.postrm
@@ -17,7 +17,7 @@ if [ "$1" = "purge" ] ; then
 	rm -rf /var/cache/gdm
         if getent passwd Debian-gdm >/dev/null; then
                 if [ -x /usr/sbin/deluser ]; then
-                        deluser --system Debian-gdm
+                        deluser --system Debian-gdm || echo "Could not remove Debian-gdm user."
                 fi
         fi
         if getent group Debian-gdm >/dev/null; then
